name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-affected-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Identify affected apps
        id: identify-affected-apps
        run: |
          CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r HEAD^ HEAD)
          AFFECTED_APPS=""
          if echo "$CHANGED_FILES" | grep -q "^app1/"; then
            AFFECTED_APPS="app1"
          fi
          if echo "$CHANGED_FILES" | grep -q "^app2/"; then
            AFFECTED_APPS="$AFFECTED_APPS app2"
          fi
          echo "::set-output name=affected_apps::$AFFECTED_APPS"

      - name: Install dependencies and build affected apps
        run: |
          for app in ${{ steps.identify-affected-apps.outputs.affected_apps }}; do
            cd $app
            npm install
            npm run build
            # Add deployment steps for each app here
            cd ..
          done
