name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-affected-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies for app1
        run: |
          cd app1
          npm install

      - name: Build app1
        run: |
          cd app1
          npm run build

      # Add deployment steps for app1 here

      - name: Install dependencies for app2
        run: |
          cd ../app2
          npm install

      - name: Build app2
        run: |
          cd ../app2
          npm run build

      # Add deployment steps for app2 here
